version: '3.8'

volumes:
  jenkins-vol:
    name: jenkins-volume
    driver: local

services:
  jenkins:
    image: jenkins/jenkins:lts-jdk8
    container_name: jenkins
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - ${JENKINS_PORT}:8080
      - 50000:50000
    volumes:
      - jenkins-vol:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
